production:
  sessions:
    default:
      uri: <%= ' mongodb://api-test:api-test@ds027729.mongolab.com:27729/dish' %>
      options:
        max_retries: 30
        retry_interval: 1
        timeout: 30

development:
  sessions:
    default:
      uri: <%= 'mongodb://api-test:api-test@ds027729.mongolab.com:27729/dish' %>
      options:
        max_retries: 30
        retry_interval: 1
        timeout: 30